### ISSUE TITLE
Problem with linking Upstream Storage and Routing Downstream 

### ISSUE THREAD

**Issue by glenncampagna** [HARPgroup/HARParchive#1213]
**Script:** https://github.com/HARPgroup/HARParchive/blob/master/HARP-2023-Summer/WaterAvailability/WaterAvailability_CaseStudies.Rmd

- Storage is found upstream and then summed using this code chunk: 
```
for (i in 1:nrow(metric_data)) {
  ups_storage <- fn_extract_basin(storage_byseg, metric_data$riverseg[i]) #find if any upstream segments have storage
  if (nrow(ups_storage) > 0) {
    ups_storesegs <- data.frame(rivseg = ups_storage$riverseg)
    ups_df <- sqldf("select a.*
                    from storage_byseg as a
                    where riverseg in (select rivseg from ups_storesegs)") 
    metric_data$SminL30mg_apx_ups[i] <- sum(ups_df$SminL30mg_apx_local) - 
      metric_data$SminL30mg_apx_local[i] #dont double count storage 
    metric_data$SminL90mg_apx_ups[i] <- sum(ups_df$SminL90mg_apx_local) - 
      metric_data$SminL90mg_apx_local[i]
    metric_data$SminL30mg_nex_ups[i] <- sum(ups_df$SminL30mg_nex_local)- 
      metric_data$SminL30mg_nex_local[i]
    metric_data$SminL90mg_nex_ups[i] <- sum(ups_df$SminL90mg_nex_local)- 
      metric_data$SminL90mg_nex_local[i]
  }
```
- Where:
  - `metric_data` contains all vahydro-1.0 segments and all metrics for them
  - `storage_byseg` contains all segments that have storage which has been summed by segment 

- Testing process:
  - Find row of `metric_data` for a segment that is failing to see upstream storage 
  - Test that row in code chunk, is storage upstream being found? 
  - [ ] Do this for each case study where we see failure of linking upstream storage

**Comment by COBrogan** [comment]
@glenncampagna , it looks like the issue was in the beginning of that for loop. If I'm not mistaken, it seems like 
```ups_storage <- fn_extract_basin(storage_byseg, metric_data$riverseg[i]) ``` will not capture all upstream segments of metric_data$riverseg[i] because some of them are missing storage and are thus not in storage_byseg. fn_extract_basin appears to currently be set-up to look upstream in order. As an example, it can find river seg 0001_0000 as upstream of 0000_0000 if they are both in the dataset. But, if we have another segment further upstream like 0004_0003, fn_extract_basin will only recognize this as an upstream segment of 0000 _0000if segments 0003_0002, 0002_0001, and 0001_0000 are in the data frame.

In this case, storage_byseg only has data for river segments that have storage. If we are looking at a particular downstream segment like Bath County (6590_6600), fn_extract_basin won't be able to trace the river upstream if there are any upstream segments that are missing storage. 

So, I think we can get this working by instead pointing fn_extract_basin to look at a more complete list of riversegments. We can get that list from our river segment view. Unfortunately, this process is now _excruciatingly_ slow. fn_extract_basin is recursive and has a lot of loops in it. R is built on vectors. While and for loops will really bog it down, so I'm wondering if my application of fn_extract_basin is the best tool for this. @rburghol do you have any other ideas for getting a list of upstream segments for each watershed in metric_data (~580)? I could dig into fn_extract_basin. In particular, it looks like we could speed up fn_upstream and likely fn_upstreamAll if we were to vectorize the ~6 or so loops. Would take some time, but could be worth it. My current "fix" is in  #1216 , but it is very slow...

Also, @glenncampagna this code is very well documented. I really appreciated reading through the whole script as it helped me get caught up to speed. Keep up the great work!

**Comment by rburghol** [comment]
God sleuthing. The fast and easy fix is to request multiple variables in
addition to storage, and the first variable should be something like Qout
which everything has.

The alternative is to adjust the join in the ciew that drives
om_vahydro_metric_grid() to return null if the metric is missing.

**Comment by glenncampagna** [comment]
Thank you @COBrogan for digging into this and providing that thorough explanation as to why this is happening. Your fix makes sense to me and testing your branch shows that it does fix the problem of getting all upstream storage. Regarding the very long processing time, we could organize this process how we do our regional summaries and generate and save data frames that will then be used in the RMD, so the time-consuming data processing doesn't have to happen every time the script is run. For example, saving `metric_data` after linking upstream storage, and then reading that file to get the needed data

I know having good documentation is crucial for this Water Availability project so it's good to hear that it has been helpful so far

**Comment by COBrogan** [comment]
Thanks for your patience @glenncampagna . See PR #1220 for the updated code. This works with the latest version of hydrotools, which you will have to reinstall to get the update. Using the more efficient fn_extract_basin(), the metric_data loop should be able to find upstream storage for all segments within 10-20 seconds. We could get this to run even faster with some other modifications, but I wanted to keep a lot of the existing code in place so you didn't have to search around for your code. However, I'm happy to help cut this time down further if you're interested in learning about some of the methods we used to fix up fn_extract_basin(). Let me know if you have any issues! And keep up the good work!

**Comment by glenncampagna** [comment]
### Removing and re-installing hydrotools -- Error: corrupt
I tried uninstalling and re-installing hydrotools with 
```
remove.packages('hydrotools')
install.packages("devtools")
library("devtools")
install_github("HARPgroup/hydro-tools")
library("hydrotools")
```
and then I get this error when trying to run the RMD
`Error: lazy-load database '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/hydrotools/R/hydrotools.rdb' is corrupt`
I followed the directions in the hydro-tools repo. Where did I go wrong? This currently limits my ability to do any Water Availability work

**Comment by glenncampagna** [comment]
### Resolution to comment above 
The problem mentioned in the above comment about re-installing hydrotools was resolved by entering `1` the prompted to update all dependent packages, and the doing a hard restart of Rstudio afterward. The improved efficiency of fn_extract_basin is pretty amazing @COBrogan

**Comment by COBrogan** [comment]
I'm glad you were able to get hydrotools again. The error you encountered honestly may have been my fault. I had built the package incorrectly a few times after telling you everything was ready to go. This was corrupting some documentation files and making it impossible to re-install. I finally fixed it late in the evening and _maybe_ that is why it worked when you entered ```1```. Not sure, but either way it's good to hear everything is up and running smoothly!

**Comment by durelles** [comment]
[like]  Scott, Durelle reacted to your message:
________________________________

**Comment by rburghol** [comment]
@glenncampagna -- not sure where to stash info about the North Anna re-run of runid zero, so here it is!  That re-run completed yesterday afternoon and it appears that everything went great.  Please let me know how it works out when you get a chance!
