### ISSUE TITLE
Update fn_all_upstream() to truly get *all* upstream

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#20]
- We want this function, or a variant to get all tributaries in the watershed, not just an arbitrary main stem.
- verify the name, and let's create a new copy in the hydrotools repo (eventually).
- There is a family of functions in the om repository **findTribs()**, **findNextDown()**, and **findNextUp()** that does this - see om [lib_nhdplus.php](https://github.com/HARPgroup/om/blob/master/php/lib/lib_nhdplus.php)

**Comment by alexwlowe** [comment]
Hey team,

As it turns out, fn_all_upstream() does in fact truly get all upstream river segments!! We made a new script that we have right now is able to pull all the upstream functions. It is super slow again now though, so we will need to either figure out a way to speed it up or use the functions in the om repository listed above.

Take a look at this skeleton plot that we were able to make: 
![image](https://user-images.githubusercontent.com/66274261/111543769-e2a8ae80-8749-11eb-8579-c78ae481b3a7.png)

Maybe next week Rob could give us a demo of the above functions, because we looked at the scripts and were all extremely confused by the php language syntax.
