### ISSUE TITLE
Integrate latest analysis scripts from HARPArchive into meta_model `hsp2_cbp6` and `hspf_cbp6` in the chain `river/analyze` (@glenncampagna @jdkleiner @juliabruneau )

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HARParchive#742]
- See current: https://github.com/HARPgroup/meta_model/blob/main/models/hsp2_cbp6/river/analyze/
- The 2 scripts that will be integrated are `summarize_values.R` and `summarize_figures.R`
  - the contents will be replaced into hsp_hydr_analysis.R from summarize_values.R
  - new figure generation script included: hsp_hydr_plots.R (summarize_figures.R)
- New organization of the meta-model after implementation of wd, demand and ps processing will have this be put into `meta_model/models/hsp*_cbp6/river/analyze/04_analysis`

**Comment by glenncampagna** [comment]
### Last step for hspf analysis
- Now that we have a daily hydr csv for hspf, analysis is run in the meta_model but stops at FDC creation because hspf lacks Qbaseline
- Qbaseline is absent because it relies on withdrawals which are not currently exported from hspf, so we decided we will substitute demand for wd in hspf for a simple fix
- Withdrawal will equal demand for the vast majority of data except droughts when not all demand can be met 
- [ ] Make this change in the meta-model version of `hsp_hydr_conversion.R` and have action depend on presence of hsp2-unique  columns (RO, O3)
- [ ] Document this fix/assumption in Rscript comments and in meta-model
- [ ] Test meta-model analysis for hspf with this fix and verify FDC exported to vahydro
