### ISSUE TITLE
Non-conforming cases of sub-watershed resegmentation

### ISSUE THREAD

**Issue by juliabruneau** [HARPgroup/HARParchive#747]
### Re-segmenting a tidal segment.
Subwatersheds in cbp6 segments that drain to tidal waters (ends with **0000**) cannot get stream hydro parameters from the parent watershed because the tidal segments lack certain data. Example: `./run/resegment/add_sub_watershed.bat YL0_7010_0000_beaverdam YL0_7010_0000 cbp-6.0 subsheds 17.57` will fail at the end when using `copy_parent.R`.  However, since a tidal segment HUC10 may still have non-tidal tributaries, we need to be able to simulate them.  
Details:
- Segments that end in `0000` have no river channel simulation.  
   - The land runoff/etc goes directly to estuary model
   - No entries in `input/param/river/[PARAMETERS]/ADCALC.csv`, `HYDR.csv` and `SCRORG.csv`
- There ARE entries in `config/catalog/geo/[GEO]/rivernames.csv`
- There ARE entries in `config/catalog/geo/[GEO]/land_water_area.csv`
- There ARE entries in `input/scenario/river/land_use/land_use_2013VAHYDRO2018615.csv`
   - AND, the land use DOES get re-segmented when running `add_sub_watershed.bat`
**Manually copying HYDR/SCRORG and ADCALC**
- I split the 2nd half of `add_sub_watershed.bat` into another script `copy_ad_hy_sc`
   - This script handles just those things that are in an existing riverine simulation.
   - `add_sub_watershed.bat` calls `copy_ad_hy_sc` after doing the first part.
- If `add_sub_watershed.bat` fails in the hydro parameters part, you can run `copy_ad_hy_sc` manually with a different downstream source to copy from, since the resegmentation has already been accomplished. Like so:
   - `./run/resegment/copy_ad_hy_sc YL0_7012_7010 YL2_6580_0001 cbp-6.1 subsheds`

### Nested Re-Segmentation
- Note: since these failed partway thru, needed to go in and delete, 
- Ex: `JB0_7050_0001_cranstons_mill`
   - flows into `JB0_7050_0000_yarmouth`
      which flows into `JB0_7050_0000`
- solution:
   - re-segment `JB0_7050_0000_yarmouth`, then resegment `JB0_7050_0001_cranstons_mill` from the subwatershed that results.
   - use Diascund Creek `JB0_7052_0001` as the template for default stream parameters.
      - `./run/resegment/add_sub_watershed.bat JB0_7050_0000_yarmouth JB0_7050_0000 cbp-6.1 subsheds 10.11 JB0_7052_0001 blank`
      - Note: returned `JB0_7054_7050` for Yarmouth below Cranstons, and renamed, so need to use that in the next step.
      - `./run/resegment/add_sub_watershed.bat JB0_7050_0001_cranstons_mill JB0_7054_7050 cbp-6.1 subsheds 6.99`

**Comment by rburghol** [comment]
Details:
- Segments that end in `0000` have no river channel simulation.  
   - The land runoff/etc goes directly to estuary model
- There ARE entries in `config/catalog/geo/[GEO]/rivernames.csv`
- There ARE entries in `config/catalog/geo/[GEO]/land_water_area.csv`
- There ARE entries in `input/scenario/river/land_use/land_use_2013VAHYDRO2018615.csv`
   - AND, the land use DOES get re-segmented when running `add_sub_watershed.bat`
- Fails at `copy_parent.R` as noted above, but:
   - Parent (`YL0_7010_0000`) does have `input/param/transport/wF180615RXAPXXXW_l2w.csv`
   - Parent (`YL0_7010_0000`) does have `input/param/transport/wF180615RXAPXXXW_s2r.csv`
   - does NOT have SCRORG, HYDR, ADCALC
- Ways to resolve: yes, "Duplicating information from another YL -file?"

**Manually copying HYDR/SCRORG and ADCALC**
- I split the 2nd half of `add_sub_watershed.bat` into another script `copy_ad_hy_sc`
   - This script handles just those things that are in an existing riverine simulation.
   - `add_sub_watershed.bat` calls `copy_ad_hy_sc` after doing the first part.
- If `add_sub_watershed.bat` fails in the hydro parameters part, you can run `copy_ad_hy_sc` manually with a different downstream source to copy from, since the resegmentation has already been accomplished. Like so:
   - `./run/resegment/copy_ad_hy_sc YL0_7012_7010 YL2_6580_0001 cbp-6.1 subsheds`

**Comment by rburghol** [comment]
Little Creek Reservoir
```
./run/resegment/add_sub_watershed.bat vahydrosw_wshed_JB0_7050_0000_little_creek JB0_7050_0000 cbp-6.1 subsheds 5.098 JB0_7052_0001 blank
riverseg=JB0_7056_7050
 Rscript run/resegment/ftable_creation.R $riverseg local_channel vahydro-1.0 "/opt/model/p6/vadeq/input/param/river/vahydro_2022/ftables/"
/opt/model/meta_model/run_model hsp2_cbp6 $scenario $riverseg tmp/scratch/rwb river prep 01_run_rug

```

**Comment by rburghol** [comment]
- `Rscript run/resegment/subsheds_naming.R JL6_7440_7430_harris_creek /opt/model/p6/vadeq/config/catalog/geo/vahydro/rivernames.csv cbp-6.1 JL6_7440_7430`
- `Rscript run/resegment/ftable_creation.R JL6_7441_7440 manual vahydro-1.0 /opt/model/p6/vadeq/input/param/river/vahydro_2022/ftables/ 29.9 11372 2 0.00120395`
- `./run/resegment/add_sub_watershed.bat JL6_7441_7440 JL6_7440_7430 cbp-6.1 subsheds 29.9 JB0_7052_0001 blank`

**Comment by rburghol** [comment]
Ivy Creek ows-watershed-dash-info/68185
```
./run/resegment/add_sub_watershed.bat JL2_6441_6520_ivy_creek JL2_6441_6520 cbp-6.1 subsheds

```
